package com.vunke.tv_sharehome.greendao.dao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WHITE_CONTANCT".
 */
public class WhiteContanct {

    private Long whiteId;
    private String face;
    private String companyPhone;
    private String userName;
    private String email;
    private String groupId;
    private String firstName;
    private String lastName;
    private Boolean isRcs;
    private String homePhone;
    private String contactName;
    private java.util.Date createTime;

    public WhiteContanct() {
    }

    public WhiteContanct(Long whiteId) {
        this.whiteId = whiteId;
    }

    public WhiteContanct(Long whiteId, String face, String companyPhone, String userName, String email, String groupId, String firstName, String lastName, Boolean isRcs, String homePhone, String contactName, java.util.Date createTime) {
        this.whiteId = whiteId;
        this.face = face;
        this.companyPhone = companyPhone;
        this.userName = userName;
        this.email = email;
        this.groupId = groupId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.isRcs = isRcs;
        this.homePhone = homePhone;
        this.contactName = contactName;
        this.createTime = createTime;
    }

    public Long getWhiteId() {
        return whiteId;
    }

    public void setWhiteId(Long whiteId) {
        this.whiteId = whiteId;
    }

    public String getFace() {
        return face;
    }

    public void setFace(String face) {
        this.face = face;
    }

    public String getCompanyPhone() {
        return companyPhone;
    }

    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Boolean getIsRcs() {
        return isRcs;
    }

    public void setIsRcs(Boolean isRcs) {
        this.isRcs = isRcs;
    }

    public String getHomePhone() {
        return homePhone;
    }

    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

}
